version: '3.8'

services:
  # --- SERVIÇO 1: A API (Backend) ---
  text2sql-api:
    build:
      # Contexto: A pasta atual
      context: .
      # Dockerfile: O arquivo que renomeamos
      dockerfile: Dockerfile.api
    env_file:
      - .env
    # A porta da API (8000) SÓ precisa ser vista pelos outros
    # contêineres. Não precisamos mais expô-la para o seu PC.
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./demo.db:/code/demo.db

  # --- SERVIÇO 2: A INTERFACE (Frontend) ---
  frontend:
    build:
      # Contexto: A pasta 'frontend'
      context: ./frontend
      # Dockerfile: O arquivo que criamos
      dockerfile: Dockerfile.frontend
    ports:
      # Mapeia a porta 8501 (Streamlit) do contêiner
      # para a porta 8501 do seu computador.
      - "8501:8501"
    restart: unless-stopped
    # O frontend depende da API. Ele só deve iniciar
    # depois que a API estiver pronta.
    depends_on:
      - text2sql-api